# @brief   cp1252_escape Makefile for Unix like environment.
# @author  eel3
# @date    2014/06/23
#
# @note
# - 

app        := escape
CFLAGS     += -Wall -ansi -pedantic

.PHONY: all
all: $(app)

.PHONY: clean
clean:
	$(RM) $(app)
